version: '3.8'
services:
  database-banking:
    image: 'bitnami/postgresql'
    container_name: database-banking
    ports:
      - '5432:5432'
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=banking
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    networks:
      - banking-network

volumes:
  postgresql_data:
    driver: local

networks:
  banking-network:
